### ISSUE TITLE
No readings when called from function

### ISSUE THREAD

**Issue by Tech500** [wollewald/INA226_WE#10]
Project uses EByte transievers to wake deep sleeping ESP32, then swtich battery on/off and using INA226 monitor the battery.

[Project code:](https://gist.github.com/Tech500/a73efc4a6fc4dcb519785de8998541bd)

Can not find a way to initialize INA226; issue maybe, deep sleeping interfers with initalizing process.

[Library example "Triggered.ino" results:  ](https://drive.google.com/file/d/14lMoiImN8K73HAB8RfpGlNqvJPnCVGF2/view?usp=sharing)

[Project call from updaedfunction results:  ](https://drive.google.com/file/d/14nEdgD2Yt_27hmvNZ8nspIv-zHjIOtKz/view?usp=sharing)

Monitoring voltage with DMM across load:   When load is on 5.54 V, load is off 8.4 mV.

William

**Comment by wollewald** [comment]
@Tech500 , I have reduced the receiver code, so that it just woke up periodically and did an INA226 measurement. I found the same issue like you. When I took out gpio_hold_en(GPIO_NUM_21); it worked on my side. Somehow sleep, this function and I2C interefere. 
The fastest way to check is to take different I2C Pins. It worked on my side with Wire.begin(22,18);
Hope this helps.

**Comment by Tech500** [comment]
Thank you wollewald; appreciate the fast response, your time, and knowledge!

Had to keep "gpio_hold_en(GPIO_NUM_21);" it is required for the EByte transcievers.  I did change out the "Wire.begin(22, 21);" replacing the 21 with 18.  Worked well!

[Crafted a short video of project:](https://drive.google.com/file/d/14qe1jkAmEUMFsySnD64qM3dUfmlNhTbm/view?usp=sharing)

William
