### ISSUE TITLE
Multiple INA226s

### ISSUE THREAD

**Issue by grego1981** [wollewald/INA226_WE#3]
Hi and thank you for your work!

Is it possible to use this library whenhaveing multiple INA226 modules? If so how can this be achieved?

Thank you!

**Comment by wollewald** [comment]
You can use up to four INA226 modules. Most of them should have I2C address jumpers:

![ina226](https://user-images.githubusercontent.com/41305162/108219732-4a151380-7136-11eb-9eba-7609ab58790b.png)

The addresses are as follows:

0x40: A0, A1 open
0x41: A0 closed, A1 open
0x44: A0 open, A1 closed
0x45: A0, A1 closed

Then you create four instances of INA226_WE. Using interrupt functions could be an issue, depending on the number of interrupt pins that your MCU has. You may need to query the alert pin status with non-interrupt I/O pins. 

And with more than four it would become difficult. You would need to switch some of them on / off, in a kind of multiplxing system. 

Hope this helps!?

**Comment by grego1981** [comment]
Thanks this helps a lot! For the instances I use the code below?
INA226_WE ina226_1(I2C_ADDRESS_1);
INA226_WE ina226_2(I2C_ADDRESS_2);

For the alert pins I was hoping to use them as inputs to digital pins to just raise an alert not as interrupts, do you think it is possible?

Based on the schematics you may connect up to 16 INA216s you just use some other connections (botch wires I imagine) to cater for combinations not covered by the board! I'll test and post!

**Comment by grego1981** [comment]
FYI just tested other combinations as per data sheet and they work fine! I 'll update when I'll actually have more than 4 devices online at the same time (I plan 5 of them)

**Comment by wollewald** [comment]
Great that it works so far. And yes, you can work with digital pins, which you then have to query with digitalRead. 

Adding the fifth INA226 is a bit more tricky. You might add it as INA226_WE ina226_5(I2C_ADDRESS_1); and then you would have to switch ina226_1 and ina226_5 on and off, maybe using a transistor. But every time you turn one of them on you also have rewrite the settings again. 

What also might work, but I have not tried yet, is to use a transistor as a switch directly in the I2C line (the SDA line should be sufficient). Do you know what I mean? Then you would not turn off the INA226 completely.

**Comment by wollewald** [comment]
Hello, with my latest update, you can now also use the two ESP32 I2C busses. I close this issue now.

**Comment by wollewald** [comment]
Hi @steveasm,

ina226, ina226p1, ina226p2 etc. are pointers to objects of the class INA226_WE. You can create an array this way:
INA226_WE* ina226Sensors[] = {&ina226, &ina226p1, &ina226p2, ......};

When you use functions for the array elements, you have to take the arrow operator instead of the point operator, e.g.:
ina226Sensors[2]->getCurrent_mV();

Hope this helps.

**Comment by steveasm** [comment]
Thanks - enjoy your trip!

That worked (tried the first method). 

One more question when you return. I would like to print this but cannot seem to figure out how to make it a string.

for (int i=0; i<=10; i++) {
	if (!ina226Sensors[i].init()) {
        Serial.println("Failed to init " + String(ina226Sensors[i]) + ". Check your wiring or its I2C address.");
	while (1) {}
	}
} 

Also, the point operator seems to work when I do it this way instead of the arrow operator.

**Comment by wollewald** [comment]
Yes, String(ina226Sensors[i]) won't work. I would do it like this:

Serial.print("Failed to init ina226Sensors[");
Serial.print(i);
Serial.prinln("]. Check your wiring or its I2C address.");

Or with snprintf() to have it shorter. Or printf() if available on your board.

https://wolles-elektronikkiste.de/en/formatted-output#sprintf_and_co

**Comment by steveasm** [comment]
Thanks for that!

I was thinking of setting up an array like this 

float sensorCurrent [10] = {0,0,0,0,0,0,0,0,0,0}; 

and then iterating through in the loop to populate the array values.

for (int i=0; i<=10; i++) {
	sensorCurrent[i] = ina226Sensors[i].getCurrent_mA();
	}

but because there are 10 sensors, do you suggest changing the default averaging or timing?

**Comment by steveasm** [comment]
Sorry, what I meant was in your example for continuous there are settings for averaging and conversion time.

  /* Set Number of measurements for shunt and bus voltage which shall be averaged
  /* Set conversion time in microseconds

My overall aim is to detect when amperage goes from zero to at least 100 ma (or reverse) and stays there for 200-300 milliseconds (to eliminate spurious readings).  

I am thinking a way to do this would be to increase the number of measurements that are averaged and the conversion time. 

Since the code will be iterating through for 10 instances, I am not sure if it matters how much time it takes for each instance to do its work.

**Comment by steveasm** [comment]
Just wanted to close the loop on this one if anyone else is interested and trying to use multiple INA226 modules.

BTW, does anyone know if the polarity of the power being measured by the INA226 can be reversed? I assumed not because of the "In+" and "In-" labels but wanted to check. 

I did solder a 0.01 resistor in parallel with the one on the board to allow higher current readings. Also, some of the modules ordered from Amazon had A1 tied to VS, so the options of what other addresses they could be set to were limited to 0x45, 0x46 and 0x47.

the code looked like this (and worked)

** in the definitions section
// define the INA226 current sensors
//                                                                    A1   A0
#define I2C_ADDRESS0 0x40   // 1000000   GND  GND   main power/overload sensor
#define I2C_ADDRESS1 0x41   // 1000001   GND  VS    position1
#define I2C_ADDRESS2 0x42   // 1000010   GND  SDA   position2
#define I2C_ADDRESS3 0x43   // 1000011   GND  SCL   position3
#define I2C_ADDRESS4 0x44   // 1000100   VS   GND   position4
#define I2C_ADDRESS5 0x45   // 1000101   VS   VS    position5
#define I2C_ADDRESS6 0x46   // 1000111   VS   SDA   position6
#define I2C_ADDRESS7 0x47   // 1000101   VS   SCL   position7
#define I2C_ADDRESS8 0x48   // 1001000   SDA  GND   position8
#define I2C_ADDRESS9 0x49   // 1001001   SDA  VS    position9
#define I2C_ADDRESS10 0x4A  // 1001001   SDA  VS    position10

float SensorCurrentmA[] = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
const int NumOfSensors = sizeof(SensorCurrentmA) / sizeof(SensorCurrentmA[0]);  // Calculate number of sensors
INA226_WE ina226Sensors[NumOfSensors];

** in the Setup function
	ina226Sensors[0] = INA226_WE(I2C_ADDRESS0);
	ina226Sensors[1] = INA226_WE(I2C_ADDRESS1);
	ina226Sensors[2] = INA226_WE(I2C_ADDRESS2);
	ina226Sensors[3] = INA226_WE(I2C_ADDRESS3);
	ina226Sensors[4] = INA226_WE(I2C_ADDRESS4);
	ina226Sensors[5] = INA226_WE(I2C_ADDRESS5);
	ina226Sensors[6] = INA226_WE(I2C_ADDRESS6);
	ina226Sensors[7] = INA226_WE(I2C_ADDRESS7);
	ina226Sensors[8] = INA226_WE(I2C_ADDRESS8);
	ina226Sensors[9] = INA226_WE(I2C_ADDRESS9);
	ina226Sensors[10] = INA226_WE(I2C_ADDRESS10);

	for (int i = 0; i < NumOfSensors; i++) {
		if (!ina226Sensors[i].init()) {
			Serial.print("Failed to init ");
			Serial.print(i);
			Serial.println(" Check your wiring or its I2C address.");
			while (1) {}
		}
	}

	for (int i = 0; i < NumOfSensors; i++) {
		ina226Sensors[i].setResistorRange(0.0091, 9);  //because I soldered a 0.01 shunt resistor in parallel
	}

	for (int i = 0; i < NumOfSensors; i++) {
		ina226Sensors[i].waitUntilConversionCompleted();  //if you comment this line the first data might be zero
	}

** in the Loop or a function to read the sensors
	for (int i = 0; i < NumOfSensors; i++) {  
		SensorCurrentmA[i] = ina226Sensors[i].getCurrent_mA();
        }

**Comment by wollewald** [comment]
@steveasm: You can swap In+ and In- and get negative shunt voltages and currents accordingly. The power is always positive. A negative power would at least not make much sense. 

What would not really work is when you have a reversed current flow from the load to In- to In+ (which is similar to the low-side setup) because the bus voltage which is measure at In- vs. GND ist not correct (almost zero). But you could still measure the current. 

Thanks for sharing your experience with 11 sensors - not bad!

**Comment by steveasm** [comment]
quick follow up to this.  Looking at the schematic for the INA226 boards, they all seem to have 10k pull up resistors on the SCL and SDL lines. Putting these in parallel as one would do with multiple boards is going to decrease the effective resistance, isn't it?  And if one already has a 4.7k pullup as recommended, it should go down even further. Am I looking at this correctly? Is it a problem to use multiple boards, then?

**Comment by wollewald** [comment]
This is no problem. The I2C lines are pulled to HIGH. If one of the devices sends signals it opens its SDA / SCL pins (open collector / open drain) to GND. Even if you have several pull-up resistors on a line, the line will go LOW if there is one device which opens its SDA or SCL pin. 

Why do people usually recommend 4.7 k as pull-up resistor? The I2C lines have a certain (small) capacity and together with the pull-up resistor it takes a certain time to load this capacitor (tau = R x C). From this perspective, the pull-up resistor should be as small as possible. On the other hand, if one of the devices opens, there will be a current through all the pull-up resistors. From that perspective, the pull-up resistors  should be as big as possible. 4.7 k is a good compromise. 

If you have too many pull-up resistors, you might theoretically exceed the specified maximum current that is allowed to flow through the SDA / SCL pins but since every 10 k resistor adds only 0.5 mA at 5 volts you can have quite a lot. The maximum open drain current for the INA 226 is 10 mA.
