### ISSUE TITLE
Measure high current

### ISSUE THREAD

**Issue by Theo-Zhang** [wollewald/INA226_WE#4]
Can this support high current? If I want to measure high current（Up to 30A）,  how can this be achieved? Thank you !!!

**Comment by wollewald** [comment]
The limiting factor is the registers in combination with the shunt. Since you can't change the registers you can only change the shunt. Unfortunately most modules have a 0.1 ohms resistor. More seldom are INA226 module with a 0.01 ohms resistor which would allow to measure up to ~8 amperes. For 30 A you would need a shunt of ~0.0025 ohms. I haven't seen such a version. So I think your options are:
1) Connect a second shunt in parallel: 1/R_complete = 1/R_1 + 1/R_2
2) Desolder the shunt and replace it by an approriate one
3) take the bare INA226 IC and attach the shunt you like
If you apply a shunt which differs from 0.1 ohms then use "Continuous_With_Resistor_Value.ino" as a basis.
Hope that helps.

**Comment by Theo-Zhang** [comment]
Thank you. I'll try now

**Comment by Theo-Zhang** [comment]
> 限制因素是与分流器组合的寄存器。由于您无法更改寄存器，因此只能更改分流器。不幸的是，大多数模块都有一个0.1欧姆的电阻。很少使用带有0.01欧姆电阻的INA226模块，该模块最多可测量约8安培的电流。对于30 A，您需要约0.0025欧姆的分流器。我还没有看到这样的版本。所以我认为您的选择是：
> 
> 1. 并联第二个分流器：1 / R_complete = 1 / R_1 + 1 / R_2
> 2. 拆开分流器，并用合适的分流器代替
> 3. 拿起裸露的INA226 IC并连接您喜欢的分流器。
>    如果您使用的分流器与0.1欧姆不同，则以“ Continuous_With_Resistor_Value.ino”为基础。
>    希望能有所帮助。

**Comment by Theo-Zhang** [comment]
Thank you. I'll try now

**Comment by Theo-Zhang** [comment]
> The limiting factor is the registers in combination with the shunt. Since you can't change the registers you can only change the shunt. Unfortunately most modules have a 0.1 ohms resistor. More seldom are INA226 module with a 0.01 ohms resistor which would allow to measure up to ~8 amperes. For 30 A you would need a shunt of ~0.0025 ohms. I haven't seen such a version. So I think your options are:
> 
> 1. Connect a second shunt in parallel: 1/R_complete = 1/R_1 + 1/R_2
> 2. Desolder the shunt and replace it by an approriate one
> 3. take the bare INA226 IC and attach the shunt you like
>    If you apply a shunt which differs from 0.1 ohms then use "Continuous_With_Resistor_Value.ino" as a basis.
>    Hope that helps.

Thank you. I'll try now

**Comment by wollewald** [comment]
Since I have not heard anything I close this issue now.
