### ISSUE TITLE
Soft WDT reset

### ISSUE THREAD

**Issue by tjdxryx** [wollewald/INA226_WE#6]
Hi, I used Continuous_With_Resistor_Value.ino and didn't change anyting. Specific contents are as follows

Soft WDT reset

>>>stack>>>

ctx: cont
sp: 3ffffd60 end: 3fffffc0 offset: 01a0
3fffff00:  60000314 3ffee820 00000001 40202d10  
3fffff10:  3ffee820 00000000 00000000 40202d72  
3fffff20:  3ffee820 3ffee593 00000004 40202f0e  
3fffff30:  00000000 00000040 3ffee591 3ffee7d4  
3fffff40:  3fffdad0 00000006 00000002 3ffee7d4  
3fffff50:  3fffdad0 00000006 3ffee591 4020304c  
3fffff60:  40201906 3ffe884b 3ffee548 402013e8  
3fffff70:  3fffdad0 00000031 3ffee548 402015df  
3fffff80:  00000d1b 00000008 3ffee548 4020166b  
3fffff90:  3fffdad0 3ffee6b8 3ffee548 4020107c  
3fffffa0:  feefeffe 00000000 3ffee7c0 40202238  
3fffffb0:  feefeffe feefeffe 3ffe85e0 40100e4d  
<<<stack<<<

**Comment by wollewald** [comment]
Hi @tjdxryx, from the content I conclude you are using an ESP8266 based board, right? Which one exactly? Soft WDT means that the watch dog timer triggers a reset. This usually happens when the ESP8266 has nothing to do, like in empty while-loops or if it has crashed . 

I have just tried with an ESP8266 based Wemos D1 Mini Board and the sketch works as is. So I assume something is wrong with the wiring. 

Try to replace line 31 (ina226.init()) by 
````
Serial.println();
  if(!ina226.init()){
    Serial.println("INA 226 not connected!");
  }
  else{
    Serial.println("Success - INA 226 connected"); 
  }
````
This will not solve the issue but then you know at least if the INA226 connected correctly via I2C.

**Comment by wollewald** [comment]
@tjdxryx , since I did not receive further feedback I am closing this issue.
